services:
  SatisfactoryMapFrontEnd:
    image: satisfactory-map-frontend
    stdin_open: true
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./SatisfactoryMapFrontEnd:/app:delegated"
      - /app/node_modules
  SatisfactoryMapBackEnd:
    image: satisfactory-map-backend
    ports:
      - "8080:8080"
    volumes:
      - "./SatisfactoryMapBackEnd:/app"
  SatisfactoryMapDB:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=SatisfactoryMap
    volumes:
      - mydb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", localhost]
      interval: 10s
      timeout: 5s
      retries: 5
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      - PMA_HOST=SatisfactoryMapDB
    ports:
      - "80:80"
    depends_on:
      - SatisfactoryMapDB
    volumes:
      - ./themes/boodark:/var/www/html/themes/boodark
  minio:
    image: 'minio/minio:latest'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=12345678
    ports:
      - "9000:9000"
      - "8900:8900"
    volumes:
      - 'minio:/data/minio'
    command: 'minio server /data/minio --console-address ":8900"'

volumes:
  mydb-data:
  minio:
    driver: local

