services:
  SatisfactoryMapFrontEnd:
    image: satisfactory-map-frontend
    stdin_open: true
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./SatisfactoryMapFrontEnd:/app:delegated"
      - /app/node_modules
  SatisfactoryMapBackEnd:
    image: satisfactory-map-backend
    ports:
      - "8080:8080"
    volumes:
      - "./SatisfactoryMapBackEnd:/app"
  SatisfactoryMapDB:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - mydb-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      - PMA_HOST=SatisfactoryMapDB
    ports:
      - "80:80"
    depends_on:
      - SatisfactoryMapDB
    volumes:
      - ./themes/boodark:/var/www/html/themes/boodark

volumes:
  mydb-data:

